from django.urls import path

from .views import (index,
                    UserLoginView,
                    logout_view,
                    TaskTypeListView,
                    TaskTypeCreateView,
                    TaskTypeUpdateView,
                    TaskTypeDeleteView,
                    PositionListView,
                    PositionCreateView,
                    PositionUpdateView,
                    PositionDeleteView,
                    TagListView,
                    TagCreateView,
                    TagUpdateView,
                    TagDeleteView,
                    TeamListView,
                    TeamDetailView,
                    TeamCreateView,
                    TeamUpdateView,
                    TeamDeleteView,
                    ProjectListView,
                    ProjectDetailView,
                    ProjectCreateView,
                    ProjectUpdateView,
                    ProjectDeleteView,
                    TaskListView,
                    TaskDetailView,
                    TaskCreateView,
                    TaskUpdateView,
                    TaskDeleteView,
                    toggle_assign_to_task,
                    WorkerListView,
                    WorkerDetailView,
                    WorkerCreateView,
                    WorkerPositionUpdateView,
                    WorkerDeleteView,)


urlpatterns = [
    path("", index, name="index"),
    path(
        "accounts/login/",
        UserLoginView.as_view(),
        name="login"
    ),
    path(
        "accounts/logout/",
        logout_view,
        name="logout"
    ),
    path(
        "task_types/",
        TaskTypeListView.as_view(),
        name="task-type-list"
    ),
    path(
        "task_types/create/",
        TaskTypeCreateView.as_view(),
        name="task-type-create"
    ),
    path(
        "task_types/<int:pk>/update/",
        TaskTypeUpdateView.as_view(),
        name="task-type-update"
    ),
    path(
        "task_types/<int:pk>/delete/",
        TaskTypeDeleteView.as_view(),
        name="task-type-delete"
    ),
    path(
        "positions/",
        PositionListView.as_view(),
        name="position-list"
    ),
    path(
        "positions/create/",
        PositionCreateView.as_view(),
        name="position-create"
    ),
    path(
        "positions/<int:pk>/update/",
        PositionUpdateView.as_view(),
        name="position-update"
    ),
    path(
        "positions/<int:pk>/delete/",
        PositionDeleteView.as_view(),
        name="position-delete"
    ),
    path(
        "tags/",
        TagListView.as_view(),
        name="tag-list"
    ),
    path(
        "tags/create/",
        TagCreateView.as_view(),
        name="tag-create"
    ),
    path(
        "tags/<int:pk>/update/",
        TagUpdateView.as_view(),
        name="tag-update"
    ),
    path(
        "tags/<int:pk>/delete/",
        TagDeleteView.as_view(),
        name="tag-delete"
    ),
    path(
        "teams/",
        TeamListView.as_view(),
        name="team-list"
    ),
    path(
        "teams/<int:pk>/",
        TeamDetailView.as_view(),
        name="team-detail"
    ),
    path(
        "teams/create/",
        TeamCreateView.as_view(),
        name="team-create"
    ),
    path(
        "teams/<int:pk>/update/",
        TeamUpdateView.as_view(),
        name="team-update"
    ),
    path(
        "teams/<int:pk>/delete/",
        TeamDeleteView.as_view(),
        name="team-delete"
    ),
    path(
        "projects/",
        ProjectListView.as_view(),
        name="project-list"
    ),
    path(
        "projects/<int:pk>/",
        ProjectDetailView.as_view(),
        name="project-detail"
    ),
    path(
        "projects/create/",
        ProjectCreateView.as_view(),
        name="project-create"
    ),
    path(
        "projects/<int:pk>/update/",
        ProjectUpdateView.as_view(),
        name="project-update"
    ),
    path(
        "projects/<int:pk>/delete/",
        ProjectDeleteView.as_view(),
        name="project-delete"
    ),
    path(
        "tasks/",
        TaskListView.as_view(),
        name="task-list"
    ),
    path("tasks/<int:pk>/",
         TaskDetailView.as_view(),
         name="task-detail"
         ),
    path("tasks/create/",
         TaskCreateView.as_view(),
         name="task-create"
         ),
    path("tasks/<int:pk>/update/",
         TaskUpdateView.as_view(),
         name="task-update"
         ),
    path("tasks/<int:pk>/delete/",
         TaskDeleteView.as_view(),
         name="task-delete"
         ),
    path("tasks/<int:pk>/toggle-assign/",
         toggle_assign_to_task,
         name="toggle-task-assign"
         ),
    path("workers/",
         WorkerListView.as_view(),
         name="worker-list"
         ),
    path("workers/<int:pk>/",
         WorkerDetailView.as_view(),
         name="worker-detail"
         ),
    path("workers/create/",
         WorkerCreateView.as_view(),
         name="worker-create"
         ),
    path("workers/<int:pk>/update/",
         WorkerPositionUpdateView.as_view(),
         name="worker-update"
         ),
    path("workers/<int:pk>/delete/",
         WorkerDeleteView.as_view(),
         name="worker-delete"
         ),
]

app_name = "task"
